SOURCE_FILES = src/ft_is/ft_isdigit.c \
src/ft_is/ft_isprint.c \
src/ft_is/ft_isalnum.c \
src/ft_is/ft_isascii.c \
src/ft_is/ft_ispar.c \
src/ft_is/ft_isspace.c \
src/ft_is/ft_isalpha.c \
src/ft_put/ft_putunicode.c \
src/ft_put/ft_putchar_fd.c \
src/ft_put/ft_putendl_fd.c \
src/ft_put/ft_putchard_fd.c \
src/ft_put/ft_putarr_fd.c \
src/ft_put/ft_putstrd_fd.c \
src/ft_put/ft_putstr_fd.c \
src/ft_put/ft_putnbr_fd.c \
src/ft_mem/ft_calloc.c \
src/ft_mem/ft_memmove.c \
src/ft_mem/ft_memcpy.c \
src/ft_mem/ft_memset.c \
src/ft_mem/ft_memccpy.c \
src/ft_mem/ft_memdup.c \
src/ft_mem/ft_memchr.c \
src/ft_mem/ft_memcmp.c \
src/ft_mem/ft_bzero.c \
src/queue/queue_init.c \
src/queue/queue_un_init.c \
src/queue/queue_access.c \
src/linked_list/linked_list_clear.c \
src/linked_list/linked_list_map.c \
src/linked_list/linked_list_hascycle.c \
src/linked_list/linked_list_new.c \
src/linked_list/linked_list_size.c \
src/linked_list/linked_list_last.c \
src/linked_list/linked_list_iter.c \
src/linked_list/linked_list_add_front.c \
src/linked_list/linked_list_add_back.c \
src/linked_list/linked_list_delone.c \
src/get_next_line/get_next_line_utils.c \
src/get_next_line/get_next_line.c \
src/manual_reset_event/manual_reset_event.c \
src/ft_printf/default_conversions/def_handle_conversions_fge.c \
src/ft_printf/default_conversions/def_handle_conversions_cspdi.c \
src/ft_printf/default_conversions/def_handle_conversions_u_x_ux_precent_n.c \
src/ft_printf/printf_read_fomat.c \
src/ft_printf/printf_write_util.c \
src/ft_printf/printf_util.c \
src/ft_printf/printf_functions/basic.c \
src/ft_printf/printf_functions/vararg.c \
src/ft_printf/printf_functions/base.c \
src/ft_printf/printf_write_util2.c \
src/ft_printf/write_modes/ft_printf_write_buff.c \
src/ft_printf/write_modes/ft_printf_write_ft.c \
src/ft_printf/printf_handle_conversion.c \
src/ft_init/ft_init_manual_reset_event.c \
src/ft_init/ft_init_open.c \
src/ft_init/ft_init_mutex.c \
src/ft_init/ft_init.c \
src/ft_init/ft_init_mutex_attr.c \
src/ft_init/ft_init_malloc.c \
src/shared_ptr/ft_shared_ptr_access.c \
src/shared_ptr/ft_shared_ptr_init.c \
src/ft_ternary/ft_ternary_ints.c \
src/ft_ternary/ft_ternary_ptr.c \
src/ft_ternary/ft_ternary_floats.c \
src/ft_ternary/ft_ternary_uints.c \
src/ft_parse_utils/ft_parse_utils_skip.c \
src/ft_parse_utils/ft_parse_floats.c \
src/ft_parse_utils/ft_parse_utils.c \
src/ft_str/ft_split.c \
src/ft_str/ft_strmapi.c \
src/ft_str/ft_strlcpy.c \
src/ft_str/ft_substr.c \
src/ft_str/ft_strlcat.c \
src/ft_str/ft_strrchr.c \
src/ft_str/ft_strjoin.c \
src/ft_str/ft_strjoin_va.c \
src/ft_str/ft_unicode_length.c \
src/ft_str/ft_strnstr.c \
src/ft_str/ft_strchr.c \
src/ft_str/ft_strdup.c \
src/ft_str/ft_strlen.c \
src/ft_str/ft_strncmp.c \
src/ft_str/ft_unicode_tochars.c \
src/ft_str/ft_strcontains.c \
src/ft_str/ft_strtrim.c \
src/list/list_foreach.c \
src/list/list_index.c \
src/list/list_access.c \
src/list/list_clear.c \
src/list/list_init.c \
src/list/list_un_init.c \
src/ft_to/ft_toupper.c \
src/ft_to/ft_tolower.c \
src/ft_loop/ft_loop.c \
src/random/ft_error.c \
src/random/ft_get_time.c \
src/ft_math/ft_math_max.c \
src/ft_math/aabb/aabb_properties.c \
src/ft_math/aabb/aabb_contains.c \
src/ft_math/aabb/aabb.c \
src/ft_math/ft_math_min.c \
src/ft_math/ft_rand.c \
src/ft_math/quaternion/quaternion_constants.c \
src/ft_math/quaternion/quaternion_from.c \
src/ft_math/quaternion/quaternion_math.c \
src/ft_math/vec3d/vec3_constants.c \
src/ft_math/vec3d/vec3_math2.c \
src/ft_math/vec3d/vec3_math3.c \
src/ft_math/vec3d/vec3_math.c \
src/ft_math/vec3d/vec3_constants2.c \
src/ft_math/ft_math_abs.c \
src/ft_ia/ft_itoa_base.c \
src/ft_ia/ft_itoa.c \
src/ft_ia/ft_atoi.c \
src/ft_bmp/read_bmp.c \
src/ft_bmp/write_bmp.c \
